name: Build APK for arm64-v8a

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Проверяем исходный код
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Для git describe --tags --always

      # 2. Устанавливаем JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Кэшируем Gradle
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Проверяем наличие секретов
      - name: Check Secrets
        run: |
          if [ -z "${{ secrets.KEYSTORE_FILE_BASE64 }}" ]; then
            echo "Error: KEYSTORE_FILE_BASE64 secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.KEYSTORE_ALIAS }}" ]; then
            echo "Error: KEYSTORE_ALIAS secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.KEYSTORE_KEY_PASSWORD }}" ]; then
            echo "Error: KEYSTORE_KEY_PASSWORD secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.KEYSTORE_STORE_PASSWORD }}" ]; then
            echo "Error: KEYSTORE_STORE_PASSWORD secret is not set"
            exit 1
          fi
          if [ "${{ env.FIRESTACK_REPO }}" == "github" ]; then
            if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
              echo "Error: GITHUB_TOKEN secret is not set for GitHub Packages"
              exit 1
            fi
          fi
        env:
          FIRESTACK_REPO: ${{ github.event.inputs.firestackRepo || 'github' }}

      # 5. Декодируем keystore из секрета
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 -d > app/keystore.jks

      # 6. Проверяем, что keystore.jks создан
      - name: Verify Keystore File
        run: |
          if [ ! -f app/keystore.jks ]; then
            echo "Error: keystore.jks was not created"
            exit 1
          fi
          ls -l app/keystore.jks

      # 7. Создаём keystore.properties
      - name: Create keystore.properties
        run: |
          echo "keyAlias=${{ secrets.KEYSTORE_ALIAS }}" > app/keystore.properties
          echo "keyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}" >> app/keystore.properties
          echo "storeFile=app/keystore.jks" >> app/keystore.properties
          echo "storePassword=${{ secrets.KEYSTORE_STORE_PASSWORD }}" >> app/keystore.properties
          echo "Created keystore.properties:"
          cat app/keystore.properties

      # 8. Проверяем содержимое keystore.properties
      - name: Verify keystore.properties
        run: |
          if [ ! -f app/keystore.properties ]; then
            echo "Error: keystore.properties was not created"
            exit 1
          fi
          echo "Contents of keystore.properties:"
          cat app/keystore.properties
          if ! grep -q "storePassword" app/keystore.properties; then
            echo "Error: storePassword not found in keystore.properties"
            exit 1
          fi

      # 9. Выводим build.gradle для диагностики
      - name: Show app/build.gradle
        run: cat app/build.gradle

      # 10. Выводим корневой build.gradle для диагностики
      - name: Show root build.gradle
        run: cat build.gradle || echo "No root build.gradle found"

      # 11. Выводим gradle-wrapper.properties
      - name: Show gradle-wrapper.properties
        run: cat gradle/wrapper/gradle-wrapper.properties

      # 12. Выводим proguard-rules.pro
      - name: Show proguard-rules.pro
        run: cat app/proguard-rules.pro || echo "No proguard-rules.pro found"

      # 13. Очищаем Gradle кэш
      - name: Clear Gradle Cache
        run: |
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/wrapper
          ./gradlew clean --no-daemon

      # 14. Делаем gradlew исполняемым
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 15. Собираем APK
      - name: Build APK
        env:
          VERSION_CODE: ${{ github.run_number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIRESTACK_REPO: ${{ github.event.inputs.firestackRepo || 'github' }}
        run: ./gradlew clean assembleWebsiteFullRelease --stacktrace --no-daemon --no-build-cache

      # 16. Загружаем APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: rethinkdns-nightly-arm64-v8a
          path: app/build/outputs/apk/websiteFullRelease/arm64-v8a/*.apk
          retention-days: 7

      # 17. Логи для отладки при ошибке
      - name: Debug Gradle logs
        if: failure()
        run: |
          cat app/build/reports/*.log || true
          find app/build -type f -name "*.txt" -exec cat {} \;
