name: Build APK for arm64-v8a

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Проверяем исходный код
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Для git describe --tags --always

      # 2. Устанавливаем JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Кэшируем Gradle
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Проверяем наличие секретов
      - name: Check Secrets
        run: |
          if [ -z "${{ secrets.KEYSTORE_FILE_BASE64 }}" ]; then
            echo "Error: KEYSTORE_FILE_BASE64 secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.KEYSTORE_ALIAS }}" ]; then
            echo "Error: KEYSTORE_ALIAS secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.KEYSTORE_KEY_PASSWORD }}" ]; then
            echo "Error: KEYSTORE_KEY_PASSWORD secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.KEYSTORE_STORE_PASSWORD }}" ]; then
            echo "Error: KEYSTORE_STORE_PASSWORD secret is not set"
            exit 1
          fi
          if [ "${{ env.FIRESTACK_REPO }}" == "github" ]; then
            if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
              echo "Error: GITHUB_TOKEN secret is not set for GitHub Packages"
              exit 1
            fi
          fi
        env:
          FIRESTACK_REPO: ${{ github.event.inputs.firestackRepo || 'github' }}

      # 5. Декодируем keystore из секрета
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 -d > app/keystore.jks

      # 6. Копируем keystore.jks в корневую директорию и app/app/
      - name: Copy Keystore to Root Directory and app/app/
        run: |
          cp app/keystore.jks keystore.jks
          cp app/keystore.jks app/app/keystore.jks
          echo "Copied keystore.jks to root directory and app/app/"
          ls -l keystore.jks
          ls -l app/app/keystore.jks

      # 7. Проверяем, что keystore.jks создан и скопирован
      - name: Verify Keystore File
        run: |
          if [ ! -f app/keystore.jks ]; then
            echo "Error: app/keystore.jks was not created"
            exit 1
          fi
          if [ ! -f keystore.jks ]; then
            echo "Error: keystore.jks was not copied to root directory"
            exit 1
          fi
          if [ ! -f app/app/keystore.jks ]; then
            echo "Error: keystore.jks was not copied to app/app/"
            exit 1
          fi
          echo "keystore.jks files:"
          ls -l app/keystore.jks
          ls -l keystore.jks
          ls -l app/app/keystore.jks

      # 8. Создаём keystore.properties
      - name: Create keystore.properties
        run: |
          echo "keyAlias=${{ secrets.KEYSTORE_ALIAS }}" > app/keystore.properties
          echo "keyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}" >> app/keystore.properties
          echo "storeFile=keystore.jks" >> app/keystore.properties
          echo "storePassword=${{ secrets.KEYSTORE_STORE_PASSWORD }}" >> app/keystore.properties
          echo "Created keystore.properties:"
          cat app/keystore.properties
          cp app/keystore.properties app/app/keystore.properties
          cp app/keystore.properties keystore.properties
          

      # 9. Проверяем содержимое keystore.properties
      - name: Verify keystore.properties
        run: |
          if [ ! -f app/keystore.properties ]; then
            echo "Error: keystore.properties was not created"
            exit 1
          fi
          echo "Contents of keystore.properties:"
          cat app/keystore.properties
          if ! grep -q "storePassword" app/keystore.properties; then
            echo "Error: storePassword not found in keystore.properties"
            exit 1
          fi
          if ! grep -q "keyPassword" app/keystore.properties; then
            echo "Error: keyPassword not found in keystore.properties"
            exit 1
          fi
          if ! grep -q "keyAlias" app/keystore.properties; then
            echo "Error: keyAlias not found in keystore.properties"
            exit 1
          fi
          if ! grep -q "storeFile=keystore.jks" app/keystore.properties; then
            echo "Error: storeFile=keystore.jks not found in keystore.properties"
            exit 1
          fi

      # 10. Выводим build.gradle для диагностики
      - name: Show app/build.gradle
        run: cat app/build.gradle

      # 11. Выводим корневой build.gradle для диагностики
      - name: Show root build.gradle
        run: cat build.gradle || echo "No root build.gradle found"

      # 12. Выводим gradle-wrapper.properties
      - name: Show gradle-wrapper.properties
        run: cat gradle/wrapper/gradle-wrapper.properties

      # 13. Выводим proguard-rules.pro
      - name: Show proguard-rules.pro
        run: cat app/proguard-rules.pro || echo "No proguard-rules.pro found"

      # 14. Очищаем Gradle кэш
      - name: Clear Gradle Cache
        run: |
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/wrapper
          ./gradlew clean --no-daemon

      # 15. Делаем gradlew исполняемым
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 16. Собираем APK
      - name: Build APK
        env:
          VERSION_CODE: ${{ github.run_number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIRESTACK_REPO: ${{ github.event.inputs.firestackRepo || 'github' }}
        run: ./gradlew clean assembleWebsiteFullRelease --stacktrace --no-daemon --no-build-cache

      # 17. Выводим содержимое директории с APK для диагностики
      - name: List APK Output Directory
        run: |
          echo "Listing contents of app/build/outputs/apk/:"
          find app/build/outputs/apk/ -type f || echo "No files found in app/build/outputs/apk/"
          echo "Listing all APK files in project:"
          find . -type f -name "*.apk" || echo "No APK files found"

# 20. Проверяем содержимое APK (arm64-v8a)
      - name: Inspect arm64-v8a APK Contents
        run: |
          APK_PATH=app/build/outputs/apk/websiteFull/release/app-website-full-arm64-v8a-release.apk
          if [ ! -f "$APK_PATH" ]; then
           echo "Error: arm64-v8a APK not found at $APK_PATH"
           exit 1
          fi
          echo "Unzipping $APK_PATH for inspection"
          unzip -q "$APK_PATH" -d apk_contents
          echo "Contents of APK:"
          ls -lh apk_contents
          echo "Checking for critical files:"
          ls -lh apk_contents/META-INF/ || echo "No META-INF/ directory (signature missing)"
          ls -lh apk_contents/classes.dex || echo "No classes.dex"
          ls -lh apk_contents/lib/arm64-v8a/ || echo "No lib/arm64-v8a/ directory"
          ls -lh apk_contents/res/ || echo "No res/ directory"
          ls -lh apk_contents/resources.arsc || echo "No resources.arsc"

# 21. Проверяем подпись APK (arm64-v8a)
      - name: Verify APK Signature
        run: |
          APK_PATH=app/build/outputs/apk/websiteFull/release/app-website-full-arm64-v8a-release.apk
          if [ ! -f "$APK_PATH" ]; then
            echo "Error: arm64-v8a APK not found at $APK_PATH"
            exit 1
          fi
          echo "Verifying signature of $APK_PATH"
          $ANDROID_HOME/build-tools/34.0.0/apksigner verify --verbose "$APK_PATH" || {
            echo "Error: APK signature verification failed"
            exit 1
          }
          echo "APK is signed successfully"

# 22. Загружаем APK (arm64-v8a)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: rethinkdns-nightly-arm64-v8a
          path: app/build/outputs/apk/websiteFullRelease/arm64-v8a/app-website-full-release-arm64-v8a.apk
          retention-days: 7

      # 18. Загружаем APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: rethinkdns-nightly-arm64-v8a
          path: app/build/outputs/apk/**/*.apk
          retention-days: 7

      # 19. Логи для отладки при ошибке
      - name: Debug Gradle logs
        if: failure()
        run: |
          cat app/build/reports/*.log || true
          find app/build -type f -name "*.txt" -exec cat {} \;
