name: Build APK for universal

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Проверяем исходный код
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Для git describe --tags --always

      # 2. Устанавливаем JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Устанавливаем Android SDK (для apksigner)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '34'

      # 4. Кэшируем Gradle
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 5. Проверяем наличие секретов
      - name: Check Secrets
        run: |
          if [ -z "${{ secrets.KEYSTORE_FILE_BASE64 }}" ]; then
            echo "Error: KEYSTORE_FILE_BASE64 secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.KEYSTORE_ALIAS }}" ]; then
            echo "Error: KEYSTORE_ALIAS secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.KEYSTORE_KEY_PASSWORD }}" ]; then
            echo "Error: KEYSTORE_KEY_PASSWORD secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.KEYSTORE_STORE_PASSWORD }}" ]; then
            echo "Error: KEYSTORE_STORE_PASSWORD secret is not set"
            exit 1
          fi
          if [ "${{ env.FIRESTACK_REPO }}" == "github" ]; then
            if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
              echo "Error: GITHUB_TOKEN secret is not set for GitHub Packages"
              exit 1
            fi
          fi
        env:
          FIRESTACK_REPO: ${{ github.event.inputs.firestackRepo || 'github' }}

      # 6. Декодируем keystore из секрета
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 -d > app/keystore.jks

      # 7. Копируем keystore.jks и создаём костыль
      - name: Copy Keystore to Root Directory and app/app/
        run: |
          cp app/keystore.jks keystore.jks
          cp app/keystore.jks app/app/keystore.jks
          echo "Copied keystore.jks to root directory and app/app/"
          ls -l keystore.jks
          ls -l app/app/keystore.jks

      # 8. Проверяем, что keystore.jks создан и скопирован
      - name: Verify Keystore File
        run: |
          if [ ! -f app/keystore.jks ]; then
            echo "Error: app/keystore.jks was not created"
            exit 1
          fi
          if [ ! -f keystore.jks ]; then
            echo "Error: keystore.jks was not copied to root directory"
            exit 1
          fi
          if [ ! -f app/app/keystore.jks ]; then
            echo "Error: keystore.jks was not copied to app/app/"
            exit 1
          fi
          echo "keystore.jks files:"
          ls -l app/keystore.jks
          ls -l keystore.jks
          ls -l app/app/keystore.jks

      # 9. Создаём keystore.properties (костыль)
      - name: Create keystore.properties
        run: |
          echo "keyAlias=${{ secrets.KEYSTORE_ALIAS }}" > app/keystore.properties
          echo "keyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}" >> app/keystore.properties
          echo "storeFile=keystore.jks" >> app/keystore.properties
          echo "storePassword=${{ secrets.KEYSTORE_STORE_PASSWORD }}" >> app/keystore.properties
          # Костыль: копируем в корень и app/app/
          cp app/keystore.properties keystore.properties
          cp app/keystore.properties app/app/keystore.properties
          echo "Created and copied keystore.properties:"
          cat app/keystore.properties
          cat keystore.properties
          cat app/app/keystore.properties

      # 10. Проверяем содержимое keystore.properties
      - name: Verify keystore.properties
        run: |
          if [ ! -f app/keystore.properties ]; then
            echo "Error: app/keystore.properties was not created"
            exit 1
          fi
          if [ ! -f keystore.properties ]; then
            echo "Error: keystore.properties was not copied to root"
            exit 1
          fi
          if [ ! -f app/app/keystore.properties ]; then
            echo "Error: keystore.properties was not copied to app/app/"
            exit 1
          fi
          echo "Contents of keystore.properties:"
          cat app/keystore.properties
          cat keystore.properties
          cat app/app/keystore.properties

      # 11. Выводим build.gradle для диагностики
      - name: Show app/build.gradle
        run: cat app/build.gradle

      # 12. Выводим корневой build.gradle для диагностики
      - name: Show root build.gradle
        run: cat build.gradle || echo "No root build.gradle found"

      # 13. Выводим gradle-wrapper.properties
      - name: Show gradle-wrapper.properties
        run: cat gradle/wrapper/gradle-wrapper.properties

      # 14. Выводим proguard-rules.pro
      - name: Show proguard-rules.pro
        run: cat app/proguard-rules.pro || echo "No proguard-rules.pro found"

      # 15. Проверяем AndroidManifest.xml
      - name: Show AndroidManifest.xml
        run: cat app/src/main/AndroidManifest.xml || echo "No AndroidManifest.xml found"

      # 16. Очищаем Gradle кэш
      - name: Clear Gradle Cache
        run: |
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/wrapper
          ./gradlew clean --no-daemon

      # 17. Делаем gradlew исполняемым
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 18. Собираем APK
      - name: Build APK
        env:
          VERSION_CODE: ${{ github.run_number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIRESTACK_REPO: ${{ github.event.inputs.firestackRepo || 'github' }}
        run: ./gradlew clean assembleWebsiteFullRelease --stacktrace --no-daemon --no-build-cache

      # 19. Выводим содержимое директории с APK и проверяем размеры
      - name: List APK Output Directory
        run: |
          echo "Listing contents of app/build/outputs/apk/:"
          find app/build/outputs/apk/ -type f -exec ls -lh {} \; || echo "No files found in app/build/outputs/apk/"
          echo "Listing all APK files in project:"
          find . -type f -name "*.apk" -exec ls -lh {} \; || echo "No APK files found"


      # 18. Загружаем APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: rethinkdns-nightly-universal
          path: app/build/outputs/apk/websiteFull/release/app-website-full-universal-release.apk
          retention-days: 7

      # 23. Логи для отладки при ошибке
      - name: Debug Gradle logs
        if: failure()
        run: |
          cat app/build/reports/*.log || true
          find app/build -type f -name "*.txt" -exec cat {} \;
